---
- name: Install software
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - mariadb-client
    - mariadb-common
    - mariadb-server
    - percona-toolkit
    - libmariadb-dev
    - python3-mysqldb
    - python3-dev
    - python3-venv
    - python3-pip
    - supervisor
    - nginx

- name: Install redis
  include_role:
    name: geerlingguy.redis

- name: Create allianceauth user
  user:
    name: "{{ alliance_auth.user }}"
    state: present
    system: true
    home: "{{ home_dir }}"

- name: Install python modules
  pip:
    virtualenv: "{{ venv_dir }}"
    virtualenv_command: python3 -m venv
    name:
      - wheel
      - allianceauth
      - gunicorn
      - django-eveuniverse
      - aa-structures
      - aa-structuretimers
      - fittings
      - aa-mailrelay
      - aa-killtracker
      - aa-moonmining
#      - aa-discordnotify
      - aa-memberaudit
      - aa-rss-to-discord
      - allianceauth-discordbot

- name: Start MariaDB
  service:
    name: mariadb
    state: started

- name: Delete anonymous users
  mysql_user:
    user: ""
    state: absent

- name: Drop test database
  mysql_db:
    name: test
    state: absent

- name: Create allianceauth database
  mysql_db:
    name: "{{ alliance_auth.db.name }}"
    login_user: root
    login_host: localhost
    state: present

- name: Create user for allianceauth db
  mysql_user:
    name: "{{ alliance_auth.db.user }}"
    password: "{{ alliance_auth.db.password }}"
    priv: "{{ alliance_auth.db.name }}.*:ALL"
    host: localhost
    login_user: root
    state: present

- name: Run allianceauth start
  command: "{{ allianceauth }} start {{ alliance_auth.app_name }}"
  become: true
  become_user: "{{ alliance_auth.user }}"
  args:
    chdir: "{{ home_dir }}"
    creates: "{{ home_dir }}/{{ alliance_auth.app_name }}"

- name: tweak celery.py if we install aa-discordbot
  lineinfile:
    path: "{{ app_dir }}/{{ alliance_auth.app_name }}/celery.py"
    insertbefore: "# Load task modules from all registered Django app configs."
    line: "app.conf.task_routes = {'aadiscordbot.tasks.*': {'queue': 'aadiscordbot'}}"
    state: present
#  when: something to be set to show aa-discordbot

- name: get bot_conf.py for aa-discordbot
  template:
    src: files/bot_conf.py.j2
    dest: "{{ bot_conf }}"
#  when: something to be set to show aa-discordbot

- name: Generate django seed if it doesn't exist
  set_fact:
    django_seed_value: "{{ lookup('community.general.random_string', length=64) }}"
  when: ansible_local.aa.django.seed is undefined

- name: Write django seed to fact file if it doesn't exist
  copy:
    dest: /etc/ansible/facts.d/aa.fact
    content: |
      [django]
      seed={{ django_seed_value }}
  when: ansible_local.aa.django.seed is undefined

- name: Set django seed from fact file if it already exists
  set_fact:
    django_seed_value: "{{ ansible_local.aa.django.seed }}"
  when:  ansible_local.aa.django.seed is defined

- name: Deploy AA app config
  template:
    src: files/local.py.j2
    dest: "{{ app_dir }}/{{ alliance_auth.app_name }}/settings/local.py"
  notify:
    - restart apps

- name: Migrate database
  command: "{{ python }} {{ manage }} migrate"
  become: true
  become_user: "{{ alliance_auth.user }}"
  args:
    chdir: "{{ home_dir }}"

- name: Create static content directory
  file:
    path: "/var/www/{{ alliance_auth.app_name }}"
    owner: "{{ alliance_auth.user }}"
    state: directory

- name: Generate static files
  command: "{{ python }} {{ manage }} collectstatic --noinput"
  become: true
  become_user: "{{ alliance_auth.user }}"

- name: Check config
  command: "{{ python }} {{ manage }} check"
  become: true
  become_user: "{{ alliance_auth.user }}"

- name: Copy supervisor config
  copy:
    src: "{{ home_dir }}/{{ alliance_auth.app_name }}/supervisor.conf"
    dest: "/etc/supervisor/conf.d/{{ alliance_auth.app_name }}.conf"
    remote_src: yes
  notify:
    - restart supervisor

- name: Deploy supervisor app config
  template:
    src: files/app.conf.j2
    dest: "/etc/supervisor/conf.d/{{ alliance_auth.app_name }}.conf"
  notify:
    - restart apps

- name: Create nginx ssl directory
  file:
    path: /etc/ssl/self
    state: directory
    mode: '0755'

- name: Check if ssl key exists
  stat:
    path: "/etc/ssl/self/{{ alliance_auth.http_host }}.key"
  register: ssl_key

- name: Check if ssl cert exists
  stat:
    path: "/etc/ssl/self/{{ alliance_auth.http_host }}.crt"
  register: ssl_cert

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/self/{{ alliance_auth.http_host }}.key"
  when: not ssl_key.stat.exists

- name: Generate an OpenSSL Certificate Signing Request
  become: yes
  community.crypto.openssl_csr:
    path: "/etc/ssl/self/{{ alliance_auth.http_host }}.csr"
    privatekey_path: "/etc/ssl/self/{{ alliance_auth.http_host }}.key"
    common_name: "{{ alliance_auth.http_host }}"
  when: not ssl_cert.stat.exists

- name: Generate a Self Signed OpenSSL certificate
  become: yes
  community.crypto.x509_certificate:
    path: "/etc/ssl/self/{{ alliance_auth.http_host }}.crt"
    privatekey_path: "/etc/ssl/self/{{ alliance_auth.http_host }}.key"
    csr_path: "/etc/ssl/self/{{ alliance_auth.http_host }}.csr"
    provider: selfsigned
  when: not ssl_cert.stat.exists

- name: copy the nginx config file
  become: yes
  template:
    src: files/aa-nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ alliance_auth.app_name }}.conf"
  notify:
    - restart nginx

- name: create symlink
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ alliance_auth.app_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ alliance_auth.app_name }}"
    state: link
  notify:
    - restart nginx

- name: Create lock dir if needed
  file:
    name: "{{ lock_dir }}"
    state: directory

- name: Deploy data load script
  template:
    src: files/load_data.sh.j2
    dest: "{{ home_dir }}/load_data.sh"
    mode: 0755

- name: Trigger data load jobs
  command: "{{ home_dir }}/load_data.sh \"{{ data_load_jobs | join('\" \"') }}\""
